"""Render a stage-2 theme aggregation result as a self-contained HTML report.

The report uses Bulma (loaded from CDN) for styling and a small bit of vanilla
JS for interactivity: a live search filter, collapsible theme cards, and a
summary header with totals.
"""

from __future__ import annotations

import html
import json
from typing import Any


_PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
<style>
  body {{ background: #fafbfc; }}
  .theme-card {{ margin-bottom: 1.25rem; }}
  .theme-card .card-header {{ cursor: pointer; }}
  .theme-card .card-header:hover {{ background: #f5f7fa; }}
  .theme-body {{ display: none; }}
  .theme-card.is-open .theme-body {{ display: block; }}
  .theme-card.is-open .toggle-icon {{ transform: rotate(90deg); }}
  .toggle-icon {{ display: inline-block; transition: transform 0.15s ease;
                  margin-right: 0.5rem; color: #888; font-weight: bold; }}
  .quote {{ border-left: 3px solid #3273dc; padding: 0.5rem 0.85rem;
            margin: 0.5rem 0; background: #f6f9ff; border-radius: 0 4px 4px 0;
            color: #2c3e50; }}
  .quote .quote-id {{ display: block; font-size: 0.75rem; color: #7a8a99;
                       margin-bottom: 0.2rem; font-family: monospace; }}
  .pill-row .tag {{ margin: 0.15rem; }}
  .section-label {{ text-transform: uppercase; font-size: 0.75rem;
                    letter-spacing: 0.05em; color: #7a8a99;
                    margin-bottom: 0.4rem; font-weight: 600; }}
  .rationale {{ font-style: italic; color: #4a5568;
                background: #fffbea; border-left: 3px solid #f2c14e;
                padding: 0.5rem 0.85rem; border-radius: 0 4px 4px 0; }}
  .hero.is-small .title {{ font-weight: 700; }}
  .empty-msg {{ text-align: center; color: #888; padding: 2rem; }}
  .stat {{ text-align: center; padding: 0.5rem 1rem; }}
  .stat .num {{ font-size: 1.75rem; font-weight: 700; color: #3273dc; }}
  .stat .lbl {{ font-size: 0.75rem; text-transform: uppercase;
                color: #7a8a99; letter-spacing: 0.05em; }}
</style>
</head>
<body>
<section class="hero is-small is-primary">
  <div class="hero-body">
    <p class="title">Thematic Analysis — Theme Report</p>
    <p class="subtitle">Codebook version {version} · {n_themes} theme(s)</p>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="box">
      <div class="columns is-vcentered">
        <div class="column is-one-third">
          <div class="columns is-mobile is-gapless">
            <div class="column stat">
              <div class="num">{n_themes}</div>
              <div class="lbl">Themes</div>
            </div>
            <div class="column stat">
              <div class="num">{n_codes}</div>
              <div class="lbl">Codes</div>
            </div>
            <div class="column stat">
              <div class="num">{n_quotes}</div>
              <div class="lbl">Quotes</div>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="field has-addons">
            <div class="control is-expanded has-icons-left">
              <input id="search" class="input" type="text"
                     placeholder="Filter themes, codes, or quotes...">
              <span class="icon is-left">
                <i>&#128269;</i>
              </span>
            </div>
            <div class="control">
              <button id="expand-all" class="button is-light">Expand all</button>
            </div>
            <div class="control">
              <button id="collapse-all" class="button is-light">Collapse all</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="themes">
{theme_cards}
    </div>
    <p class="empty-msg" id="empty-msg" style="display:none">
      No themes match your filter.
    </p>
  </div>
</section>

<footer class="footer">
  <div class="content has-text-centered">
    <p>Generated by <strong>ta-stage2 export-themes-html</strong></p>
  </div>
</footer>

<script>
(function () {{
  const cards = Array.from(document.querySelectorAll('.theme-card'));

  function setOpen(card, open) {{
    card.classList.toggle('is-open', open);
  }}

  cards.forEach((card, idx) => {{
    if (idx < 3) setOpen(card, true);
    card.querySelector('.card-header').addEventListener('click', () => {{
      setOpen(card, !card.classList.contains('is-open'));
    }});
  }});

  document.getElementById('expand-all').addEventListener('click', () => {{
    cards.forEach(c => setOpen(c, true));
  }});
  document.getElementById('collapse-all').addEventListener('click', () => {{
    cards.forEach(c => setOpen(c, false));
  }});

  const search = document.getElementById('search');
  const emptyMsg = document.getElementById('empty-msg');
  search.addEventListener('input', () => {{
    const q = search.value.trim().toLowerCase();
    let visible = 0;
    cards.forEach(card => {{
      const hay = card.dataset.search || '';
      const match = !q || hay.indexOf(q) !== -1;
      card.style.display = match ? '' : 'none';
      if (match) {{
        visible++;
        if (q) setOpen(card, true);
      }}
    }});
    emptyMsg.style.display = visible === 0 ? '' : 'none';
  }});
}})();
</script>
</body>
</html>
"""


def _esc(s: str) -> str:
    return html.escape(s, quote=True)


def _render_theme_card(idx: int, theme: dict[str, Any]) -> str:
    name = _esc(theme.get("name", f"Theme {idx + 1}"))
    description = _esc(theme.get("description", ""))
    codes = theme.get("codes") or []
    quotes = theme.get("quotes") or []
    originals = theme.get("original_themes") or []
    rationale = theme.get("merge_rationale") or ""

    code_tags = "".join(
        f'<span class="tag is-info is-light">{_esc(c)}</span>' for c in codes
    )
    original_tags = "".join(
        f'<span class="tag is-link is-light">{_esc(t)}</span>' for t in originals
    )
    quote_blocks = "".join(
        f'<div class="quote"><span class="quote-id">{_esc(q.get("quote_id", ""))}'
        f'</span>{_esc(q.get("text", ""))}</div>'
        for q in quotes
    )

    sections: list[str] = []
    if description:
        sections.append(
            f'<p class="section-label">Description</p>'
            f'<p class="content">{description}</p>'
        )
    if originals:
        sections.append(
            f'<p class="section-label">Original themes ({len(originals)})</p>'
            f'<div class="pill-row">{original_tags}</div>'
        )
    if rationale:
        sections.append(
            f'<p class="section-label">Merge rationale</p>'
            f'<div class="rationale">{_esc(rationale)}</div>'
        )
    if codes:
        sections.append(
            f'<p class="section-label">Codes ({len(codes)})</p>'
            f'<div class="pill-row">{code_tags}</div>'
        )
    if quotes:
        sections.append(
            f'<p class="section-label">Quotes ({len(quotes)})</p>'
            f"{quote_blocks}"
        )

    body = "<hr>".join(sections) or '<p class="has-text-grey">No details.</p>'

    haystack = " ".join(
        [
            theme.get("name", ""),
            theme.get("description", ""),
            " ".join(str(c) for c in codes),
            " ".join(str(t) for t in originals),
            " ".join(q.get("text", "") for q in quotes),
            " ".join(q.get("quote_id", "") for q in quotes),
        ]
    ).lower()

    return f"""
<div class="card theme-card" data-search="{_esc(haystack)}">
  <header class="card-header">
    <p class="card-header-title">
      <span class="toggle-icon">&#9656;</span>
      <span>{name}</span>
    </p>
    <span class="card-header-icon">
      <span class="tag is-rounded">{len(codes)} codes</span>
      &nbsp;
      <span class="tag is-rounded is-primary is-light">{len(quotes)} quotes</span>
    </span>
  </header>
  <div class="theme-body card-content">
    {body}
  </div>
</div>"""


def render_themes_html(
    result: dict[str, Any],
    codebook_version: int,
    title: str = "Thematic Analysis — Theme Report",
) -> str:
    """Render a theme aggregation result dict to a self-contained HTML page."""
    themes = result.get("themes") or []
    cards = "\n".join(_render_theme_card(i, t) for i, t in enumerate(themes))
    n_codes = sum(len(t.get("codes") or []) for t in themes)
    n_quotes = sum(len(t.get("quotes") or []) for t in themes)
    return _PAGE_TEMPLATE.format(
        title=_esc(title),
        version=_esc(str(codebook_version)),
        n_themes=len(themes),
        n_codes=n_codes,
        n_quotes=n_quotes,
        theme_cards=cards or '<p class="empty-msg">No themes in result.</p>',
    )


def render_themes_html_from_json(
    result_json: str, codebook_version: int
) -> str:
    return render_themes_html(json.loads(result_json), codebook_version)
